apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kage-demo

patchesJson6902:
  - target:
      group: extensions
      version: v1beta1
      kind: Ingress
      name: one-a-backend-internal
    path: patch/ingress-host.yml

resources:
  - deploy.yml
  - ingress.yml
  - ns.yml

configMapGenerator:
  - envs:
      - one_a_config.env
    name: one-a-config-env
